name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        scala-version: [2.12.12, 2.13.3]

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Run sbt
      run: sbt ++${{ matrix.scala-version }} coverage test coverageReport

    - name: Coveralls
      continue-on-error: true
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        flag-name: run-${{ matrix.scala-version }}
        parallel: true


  coverage:
      needs: build
      runs-on: ubuntu-latest

      steps:
        - name: Coveralls Finish
          uses: coverallsapp/github-action@master
          with:
              github-token: ${{ secrets.GITHUB_TOKEN }}
              parallel-finished: true
