name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scala-version: [2.12.20, 2.13.16, 3.3.7]
    steps:
    - uses: actions/checkout@v6
    - name: Setup JDK
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: 17
        cache: sbt
    - uses: sbt/setup-sbt@v1
    - name: Run sbt
      run: sbt ++${{ matrix.scala-version }} coverage test coverageReport
    - name: Codecov
      run: bash <(curl -s https://codecov.io/bash)
