name: Deploy

on:
  push:
    tags:
    - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
          cache: sbt
      - uses: sbt/setup-sbt@v1
      - name: Run sbt
        run: sbt +test
      - name: Check assets can be published
        run: sbt +publishLocal
      - name: Check binary compatibility
        run: sbt +mimaReportBinaryIssues
      - name: Publish snowplow-scala-tracker to Maven Central
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.SONA_PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.SONA_PGP_SECRET }}
          SONATYPE_USERNAME: ${{ secrets.SONA_USER }}
          SONATYPE_PASSWORD: ${{ secrets.SONA_PASS }}